### PR TITLE
Add the payment provider logos

### PR DESCRIPTION
**Pull request by rowanmanning**
This isn't quite ready to merge yet – I need to add licence/copyright
information for each of the payment provider icons and possibly link to
more legal info.

The structure of this repo is mostly copied from flag images. The
CircleCI config is new, and will be applied to all of the image sets
once I verify that it's working here.

Resolves https://github.com/Financial-Times/ft-origami/issues/581

### CODE REVIEW

**Comment by gvonkoss** [comment]
Resolves https://github.com/Financial-Times/ft-origami/issues/581

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
Is this still required @rowanmanning ?

**Comment by JakeChampion** [comment]
If it is, we should add the labels and other origami gh actions to the repo

**Comment by JakeChampion** [comment]
Closing as no one is asking for this anymore -- https://github.com/Financial-Times/origami/issues/11#issuecomment-680821938

**Pull request closed without merging**
